name: ci

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: '1.21'
          check-latest: true

      - uses: chainguard-dev/actions/goimports@main
      - run: |
          go build ./...
          go test ./... -race
